version: '3.8'

services:
  backend:
    build: 
      context: ./django
    ports:
      - "8000:8000"
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
  
  frontend:
    build: 
      context: ./react/blogapi
    volumes:
      - react_build:/react/build


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend


volumes:
  react_build: